apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    # Increase buffer size if headers are too large
    nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
spec:
  rules:
    #host: aa5cec35bb5aa4f60b06f67b3c181ba2-1808832783.eu-central-1.elb.amazonaws.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
